-key: gitdemo
 url: https://mastiff.apifortress.com/app/api/rest/v3/00f69bd1-f172-4aab-a15b-97d676da4e6b478
 credentials:
    username: sangit@apifortress.com
    password: Apishmapi1
test_directory: /Users/sangit/Desktop/Tests/demo/devtest/tests